[package]
name = "hew-std-encoding-markdown"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::encoding::markdown â€” Markdown to HTML rendering"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[features]
export-meta = ["dep:hew-export-macro", "dep:hew-export-types"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
pulldown-cmark = "0.13"
libc = "0.2"
hew-export-macro = { path = "../../../hew-export-macro", optional = true }
hew-export-types = { path = "../../../hew-export-types", optional = true }

[dev-dependencies]
hew-runtime = { path = "../../../hew-runtime" }

[lints]
workspace = true
