[package]
name = "hew-std-net-url"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::net::url â€” URL parsing and manipulation"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
url = "2"
libc = "0.2"

[lints]
workspace = true
