[package]
name = "hew-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The Hew programming language compiler"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "compiler", "programming-language"]
categories = ["compilers", "command-line-utilities"]

[[bin]]
name = "hew"
path = "src/main.rs"

[dependencies]
hew-lexer = { path = "../hew-lexer" }
hew-parser = { path = "../hew-parser" }
hew-types = { path = "../hew-types" }
hew-serialize = { path = "../hew-serialize" }
pulldown-cmark = "0.13"
rustyline = "17"
tempfile = "3"
toml = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify = "8"

[lints]
workspace = true
