[package]
name = "hew-std-encoding-compress"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::encoding::compress â€” gzip/deflate/zlib compression"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi", features = ["vec"] }
flate2 = "1"
libc = "0.2"

[dev-dependencies]
hew-runtime = { path = "../../../hew-runtime" }

[lints]
workspace = true
