[package]
name = "hew-std-encoding-compress"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::encoding::compress â€” gzip/deflate/zlib compression"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
flate2 = "1"
libc = "0.2"

[lints]
workspace = true
