[package]
name = "hew-std-encoding-msgpack"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::encoding::msgpack â€” MessagePack encoding and decoding"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
hew-runtime = { path = "../../../hew-runtime" }
serde_json = "1"
rmp-serde = "1"
libc = "0.2"

[lints]
workspace = true
