[package]
name = "hew-std-text-regex"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::text::regex â€” regular expression matching"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
regex = "1"
libc = "0.2"

[lints]
workspace = true
