[package]
name = "hew-std-encoding-json"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::encoding::json â€” JSON parsing and generation"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
serde_json = "1"
libc = "0.2"

[lints]
workspace = true
