[package]
name = "hew-std-net-websocket"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::net::websocket â€” WebSocket client"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
tungstenite = "0.28"
libc = "0.2"

[lints]
workspace = true
