[package]
name = "hew-std-encoding-base64"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::encoding::base64 â€” Base64 encoding and decoding"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
base64 = "0.22"
libc = "0.2"

[lints]
workspace = true
