[package]
name = "hew-std-time-datetime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::time::datetime â€” date and time operations"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
hew-runtime = { path = "../../../hew-runtime" }
chrono = { version = "0.4", default-features = false, features = [
  "clock",
  "std",
] }
libc = "0.2"

[lints]
workspace = true
