[package]
name = "hew-std-time-cron"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::time::cron â€” cron expression scheduling"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
cron = "0.15"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
libc = "0.2"

[lints]
workspace = true
