[package]
name = "hew-std-net-http"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::net::http â€” HTTP client and server"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
ureq = { version = "3", default-features = false, features = ["rustls"] }
tiny_http = "0.12"
libc = "0.2"

[lints]
workspace = true
