[package]
name = "hew-std-crypto-jwt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::crypto::jwt â€” JWT encoding and decoding"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
serde_json = "1"
libc = "0.2"

[lints]
workspace = true
