[package]
name = "hew-std-crypto-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::crypto::crypto â€” cryptographic hashing, HMAC, and random bytes"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
ring = "0.17"
libc = "0.2"

[lints]
workspace = true
