[package]
name = "hew-std-net-mime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hew std::net::mime â€” MIME type detection"
readme = "README.md"
repository = "https://github.com/hew-lang/hew"
keywords = ["hew", "stdlib"]
categories = ["compilers"]

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
hew-cabi = { path = "../../../hew-cabi" }
mime_guess = "2"
libc = "0.2"

[lints]
workspace = true
